spring:
  datasource:
    url: jdbc:mysql://groomingmood.cxjgn5r5ibzk.ap-northeast-1.rds.amazonaws.com:3306/grooming_mood
    username: admin
    password: ${DB_PASSWORD}

    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
#    database: mysql
    show-sql: true
  jwt:
    secret_key: ${JWT_SECRET_KEY}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org.hibernate.SQL: debug