#name: deploy
#
#on:
#  push:
#    branches: [ "develop" ,"master"]
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    env :
#      working-directory: ./
#      APPLICATION: ${{ secrets.APPLICATION }}
#
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#
#      - name : create application yaml
#        run: |
#          touch ./src/main/resources/application.yml
#          echo "${{env.APPLICATION}}" > ./src/main/resources/application.yml
#      - uses: actions/upload-artifact@v3
#        with:
#          name: application.yml
#          path: ./src/main/resources/application.yml
#
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#
#      - name: Build with Gradle
#        run: ./gradlew build
#
#      # 도커허브 로그인
#      - name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{secrets.DOCKER_USERNAME}}
#          password: ${{secrets.DOCKER_PASSWORD}}
#
#      # 빌드 이미지 만들어 도커허브로 업로드
#      - name: build and release to DockerHub
#        env:
#          NAME: groomingmood # DockerHub 계정 명
#          IMAGE: groomingmood # Docker 이미지 이름
#          REPO: groomingmood #  DockerHub 레포 이름
#        run: |
#          docker build -t $IMAGE .
#          docker tag $IMAGE:latest $NAME/$REPO:latest
#          docker push $NAME/$REPO:latest
#      - name: Github Action to EC2
#        uses: appleboy/ssh-action@master
#        with:
#          host: ec2-52-196-145-123.ap-northeast-1.compute.amazonaws.com
#          username: ec2-user
#          key: ${{ secrets.PRIVATE_KEY }}
#          #          port: ${{ secrets.EC2_SSH_PORT }}
#          envs: GITHUB_SHA
#
#          script: |
#            docker pull groomingmood/groomingmood:${GITHUB_SHA::7}
#            docker tag groomingmood/groomingmood:${GITHUB_SHA::7} grooming-mood
#            docker stop server
#            docker run -d --rm --name server -p 8080:8080 grooming-mood